name: BossGamble
main: com.jmer05.bossgamble.BossGamble
version: 2.0.0
authors:
  - 'Josh Merlino'
depends:
  - 'Vault'
api-version: 1.15
commands:
  gambler:
    usage: /gambler <create|remove|open> [name]
    description: Manages gambler/bartenders
